title: Evan Kerr
name: Evan Kerr
description: Personal site and blog
url: "https://evankerr.me"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.28.0

minimal_mistakes_skin: "default"

search: true

markdown: kramdown

permalink: /:categories/:title/

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

author:
  name: "Evan Kerr"
  bio: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emk5389"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emk5389"
